namespace InGame {
    public enum EventType {
        Draw,
        Cast,
        Trigger,
        Resolve,
        Summon,
        LookAtDeck,
        SendToZone,
        Attack,
        Combat,
        Death,
        TributeRequirement,
        Mill,
        Spellburn,
        GainLife,
        TriggerOrdering,
        NextPhase,
        Choice,
        GainPrio,
        RefreshCardDisplays,
        TargetSelection,
        SetLifeTotal,
        PayLifeCost,
        Reveal,
        AttackCapable,
        LoseLife,
        CreateToken,
        RemoveToken,
        Destroy,
        Cost,
        EndGame,
        Discard,
        AmountSelection,
        SkipToPhase,
        Peek,
        ReturnToHand,
        Counter,
        GainControl,
        RitualOfDarknessChoice,
        GoToPhase,  // Jump directly to a specific phase (for Rewind)
        RepeatChoice,  // Post-resolution repeat choice (old style)
        RepeatAmountSelection  // Select how many times to repeat upfront (0 to max)
    }
}