namespace Server.CardProperties;

public enum EffectType {
    Draw,
    DealDamage,
    GainLife,
    Tutor,
    CreateToken,
    LoseLife,
    ModifyCost,
    Reveal,
    SendToZone,
    ForceAttack,
    ChangeStats,
    GrantKeyword,
    LookAtDeck,
    ShuffleDeck,
    Destroy,
    Counter,
    ApplySpellburn,
    CopySpell,
    Discard,
    GainControl,
    GoToPhase,
    ExtraTurn,
    EndTurn,
    ModifyHandSize,
    PlayerModifier,
    ModifyDamage,
    EndGame,
    CastCard,
    RemoveCounter,
    Mill,
    Sacrifice,
    ExileAndReturn,
    Choose,
    GrantPassive,
    Detain,
    ModifySummonLimit,
    ChangeSource,
    DiscardOpponent,
    AddCounter,
    CanAttack,
    BypassHerbLifeReduction,
    ModifyType,
    RepeatAllEffects,
    CantGainLife,
    CantAttackOrBlock,
    CantAttack,
    Attach,
    Repeat,
    SetLifeTotal,
    CantTribute,
    CardRitualOfDarkness,
    EventTriggers,
    ReplacementEffect,  // Adds a player passive that modifies zone destinations (e.g., graveyard -> exile)
    OnlySummonTribe,  // Player passive: can only summon cards of a specific tribe this turn
    GroundTactics,  // Forces opponent's summons to attack, caster controls attack target assignments
    TriggerSprout  // Manually trigger sprout keyword's herb creation for sourceCard
}