namespace Server;

public enum EventType {
    Draw,
    Cast,
    Trigger,
    Resolve,
    Summon,
    LookAtDeck,
    SendToZone,
    Attack,
    Combat,
    Death,
    TributeRequirement,
    Mill,
    Spellburn,
    GainLife,
    TriggerOrdering,
    NextPhase,
    Choice,
    GainPrio,
    RefreshCardDisplays,
    TargetSelection,
    SetLifeTotal,
    PayLifeCost,
    Reveal,
    AttackCapables,
    LoseLife,
    CreateToken,
    Destroy,
    Cost,
    EndGame,
    Discard,
    AmountSelection
}