namespace Server;

public enum EventType {
    Draw,
    Cast,
    Trigger,
    Resolve,
    Summon,
    LookAtDeck,
    SendToZone,
    Attack,
    Combat,
    Death,
    TributeRequirement,
    Mill,
    Spellburn,
    GainLife,
    TriggerOrdering,
    NextPhase,
    Choice,
    GainPrio,
    RefreshCardDisplays,
    TargetSelection,
    SetLifeTotal,
    PayLifeCost,
    Reveal,
    AttackCapables,
    LoseLife,
    CreateToken,
    RemoveToken,
    Destroy,
    Cost,
    EndGame,
    Discard,
    AmountSelection,
    SkipToPhase,
    Peek,
    ReturnToHand,
    Counter,
    GainControl,
    RitualOfDarknessChoice,  // Special event for Ritual of Darkness summon selection
    GoToPhase,  // Jump directly to a specific phase (for Rewind)
    RepeatChoice,  // Special event for repeat effects - ask if player wants to pay to repeat
    RepeatAmountSelection  // Select how many times to repeat upfront (0 to max)
}